### ISSUE TITLE
[Request] Ability to use trails from other sabers

### ISSUE THREAD

**Issue by raineio** [qqrz997/CustomSabersLite#10]
If possible, it would be nice being able to choose trails from other sabers, as when SaberFactory was actively developed, people ended up not putting trails on their sabers, leading to lots of sabers without trails on ModelSaber. [This saber](https://modelsaber.com/Sabers/?id=1687882535&pc) being one of them.

**Comment by qqrz997** [comment]
this is outside of the scope of CustomSabersLite. this mod will likely not have many extra features over the original custom sabers before naluluna took over maintaining that mod, outside of general QOL and optimization. 

If mod approval becomes less of a slog i may consider making a branch of this that has more features that people want. although, that will be less likely if SaberFactory 3 comes to fruition and also is maintained for the latest beat saber version.

**Comment by Alyng0** [comment]
May be unlikely that SF V3 comes out soon, Tonis been putting a lot of focus on SOTF (Sons of the Forests) Modding
