### ISSUE TITLE
[Feature Request] Make us able to change the trail steps

### ISSUE THREAD

**Issue by 1Alyng** [qqrz997/CustomSabersLite#18]
This is a feature "shouldnt" be that hard to do ( But again, I know jack shit about code ).
All I want is to be able to either make my trails more smooth or more jagid.

**Comment by qqrz997** [comment]
i don't see this being part of  this mod. maybe tweaks55 or a separate mod would be good for it, but not here (please don't go opening an issue on tweaks55's repo).
