### ISSUE TITLE
Mod will not load due to null saber?

### ISSUE THREAD

**Issue by EsserGaming** [qqrz997/CustomSabersLite#2]
I've been troubleshooting for the past day, and I cannot get the mod to load without the game crashing. Here's the log: [_latest.log](https://github.com/qqrz997/CustomSabersLite/files/14349088/_latest.log)

**Comment by qqrz997** [comment]
thanks for letting me know. that is very strange. i cannot reproduce this. could you try running the game with just the mod with its dependencies and/or without any custom sabers? what i think is that this could be caused by mod conflicts, or a saber that the mod doesn't like.

**Comment by EsserGaming** [comment]
> thanks for letting me know. that is very strange. i cannot reproduce this. could you try running the game with just the mod with its dependencies and/or without any custom sabers? what i think is that this could be caused by mod conflicts, or a saber that the mod doesn't like.

Sure! I'll get to testing that when I can.

**Comment by EsserGaming** [comment]
Alright, after doing some testing, I found that when I bring all of my sabers (around 30) it does that same error. I'm not sure what saber would cause the issue, but it seems to work fine with 1 saber in the folder. I started adding more and refreshing and then it crashed ~15 sabers.

**Comment by EsserGaming** [comment]
> Alright, after doing some testing, I found that when I bring all of my sabers (around 30) it does that same error. I'm not sure what saber would cause the issue, but it seems to work fine with 1 saber in the folder. I started adding more and refreshing and then it crashed ~15 sabers.

This might because of a specific saber, but I'm not sure which one yet.

**Comment by qqrz997** [comment]
could you install the version 0.4.0 of the mod i just released? it may fix your problem, and if not give me some info as to which saber is causing this. **make sure to delete UserData/CustomSabersLite.json** first before testing the new version to simulate a fresh install

**Comment by EsserGaming** [comment]
> could you install the version 0.4.0 of the mod i just released? it may fix your problem, and if not give me some info as to which saber is causing this. **make sure to delete UserData/CustomSabersLite.json** first before testing the new version to simulate a fresh install

Seems to work fine, though it still seems to break when I load more than like 10 or so sabers 🤷
