### ISSUE TITLE
[Issue] ReeSaber Incompatibility

### ISSUE THREAD

**Issue by Alyng0** [qqrz997/CustomSabersLite#3]
If you have a non Default Saber Selected, ReeSabers will not appear, ReeSabers should always be able to appear over custom saber as you can Visibility of Custom Saber on in ReeSaber, Many also use it for trails, which is not possible right now bc it gets removed

**Comment by qqrz997** [comment]
ReeSabers is not a mod i can access or test and it *vastly* proceeds CustomSabers, so there's no telling if they can be compatible.

**Comment by qqrz997** [comment]
just leaving a note here, CustomSabers reuses the default saber's behaviours, so any other mod that uses them also would likely break if using this mod.

it's not entirely off of the table that i may rewrite this mod to not use those behaviours, but it's currently not planned.
