### ISSUE TITLE
[Suggestion] Trail Width

### ISSUE THREAD

**Issue by Alyng0** [qqrz997/CustomSabersLite#5]
It would be cool if we could change the trail width, I would do it this way (if I could actually code lol) 100% would be this position for the bottom trail guide: 0.004500031
0% would be at the same position of the top trail guide and then just interpolate between that.

**Comment by qqrz997** [comment]
this is something i do want to add, i'll consider making it a bit higher priority 🌻

**Comment by qqrz997** [comment]
https://github.com/qqrz997/CustomSabersLite/releases/tag/v0.8.3
