### ISSUE TITLE
[Suggestion] Button to disable the Mod

### ISSUE THREAD

**Issue by TheRealFynn07** [qqrz997/CustomSabersLite#6]
Maybe add an toggle to fully disable the mod not just switching to default sabers :)

**Comment by qqrz997** [comment]
i will do this but, just out of curiosity, what is the reason you would want to toggle the mod?

**Comment by TheRealFynn07** [comment]
I do use your Custom Saber Mod and Nalulunas. I just want an toggle to disable/enable the mod just like nalulunasabers.

**Comment by qqrz997** [comment]
[added in 0.8.1](https://github.com/qqrz997/CustomSabersLite/releases/tag/v0.8.1)
