### ISSUE TITLE
[Bug] ScoreSaber replays with Noodle maps do not have the saber parented properly

### ISSUE THREAD

**Issue by raineaeternal** [qqrz997/CustomSabersLite#9]
It's exactly as the title says, really.

This is a pretty big issue as sometimes the SS replays are generally better than the BL replays.

**Comment by qqrz997** [comment]
i haven't tested this at all with noodleextensions but i'll get around to it, likely whenever mods are out for 1.36.0+

**Comment by qqrz997** [comment]
noodle extensions sounds like it's being worked on for latest so i should be able to test this soon. that being said, i think a change i've already made could mean that this is no longer broken.

**Comment by qqrz997** [comment]
could you link a map where you experienced this issue @raineio? i would like to see if this is still happening. noodle extensions is available for the latest version

**Comment by qqrz997** [comment]
i will close this issue now as i can't replicate it on the latest version of the mod.
